// Package users provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package users

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	OidcScopes = "oidc.Scopes"
)

// Defines values for SecretKind.
const (
	General SecretKind = "general"
	Storage SecretKind = "storage"
)

// AddPinnedProject defines model for AddPinnedProject.
type AddPinnedProject struct {
	// ProjectSlug The slug used to identify a project
	ProjectSlug ProjectSlug `json:"project_slug"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    int     `json:"code"`
		Detail  *string `json:"detail,omitempty"`
		Message string  `json:"message"`
	} `json:"error"`
}

// ExpirationTimestamp The date and time the secret is not valid anymore (this is in any timezone)
type ExpirationTimestamp = time.Time

// ModificationDate The date and time the secret was created or modified (this is always in UTC)
type ModificationDate = time.Time

// PinnedProjects The list of projects a user has pinned on their dashboard
type PinnedProjects struct {
	ProjectSlugs *[]ProjectSlugResponse `json:"project_slugs,omitempty"`
}

// ProjectSlug The slug used to identify a project
type ProjectSlug = string

// ProjectSlugResponse The slug used to identify a project
type ProjectSlugResponse = string

// SecretDefaultFilename Filename to give to this secret when mounted in Renku 1.0 sessions
type SecretDefaultFilename = string

// SecretKind Kind of secret
type SecretKind string

// SecretName The name of a user secret
type SecretName = string

// SecretPatch Secret metadata to be modified
type SecretPatch struct {
	// DefaultFilename Filename to give to this secret when mounted in Renku 1.0 sessions
	DefaultFilename *SecretDefaultFilename `json:"default_filename,omitempty"`

	// ExpirationTimestamp The date and time the secret is not valid anymore (this is in any timezone)
	ExpirationTimestamp *ExpirationTimestamp `json:"expiration_timestamp"`

	// Name The name of a user secret
	Name *SecretName `json:"name,omitempty"`

	// Value Secret value that can be any text
	Value *SecretValue `json:"value,omitempty"`
}

// SecretPost Secret metadata to be created
type SecretPost struct {
	// DefaultFilename Filename to give to this secret when mounted in Renku 1.0 sessions
	DefaultFilename *SecretDefaultFilename `json:"default_filename,omitempty"`

	// ExpirationTimestamp The date and time the secret is not valid anymore (this is in any timezone)
	ExpirationTimestamp *ExpirationTimestamp `json:"expiration_timestamp"`
	Kind                *SecretKind          `json:"kind,omitempty"`

	// Name The name of a user secret
	Name SecretName `json:"name"`

	// Value Secret value that can be any text
	Value SecretValue `json:"value"`
}

// SecretValue Secret value that can be any text
type SecretValue = string

// SecretWithId A Renku secret
type SecretWithId struct {
	DataConnectorIds UlidList `json:"data_connector_ids"`

	// DefaultFilename Filename to give to this secret when mounted in Renku 1.0 sessions
	DefaultFilename SecretDefaultFilename `json:"default_filename"`

	// ExpirationTimestamp The date and time the secret is not valid anymore (this is in any timezone)
	ExpirationTimestamp *ExpirationTimestamp `json:"expiration_timestamp"`

	// Id ULID identifier
	Id Ulid `json:"id"`

	// Kind Kind of secret
	Kind SecretKind `json:"kind"`

	// ModificationDate The date and time the secret was created or modified (this is always in UTC)
	ModificationDate ModificationDate `json:"modification_date"`

	// Name The name of a user secret
	Name                 SecretName `json:"name"`
	SessionSecretSlotIds UlidList   `json:"session_secret_slot_ids"`
}

// SecretsList A list of secrets
type SecretsList = []SecretWithId

// SelfUserInfo Information about the currently logged in user
type SelfUserInfo struct {
	// Email User email
	Email *UserEmail `json:"email,omitempty"`

	// FirstName First or last name of the user
	FirstName *UserFirstLastName `json:"first_name,omitempty"`

	// Id Keycloak user ID
	Id UserId `json:"id"`

	// IsAdmin Whether the user is a platform administrator or not
	IsAdmin bool `json:"is_admin"`

	// LastName First or last name of the user
	LastName *UserFirstLastName `json:"last_name,omitempty"`

	// Username Handle of the user
	Username Username `json:"username"`
}

// ShowProjectMigrationBanner Should display project migration banner
type ShowProjectMigrationBanner = bool

// Ulid ULID identifier
type Ulid = string

// UlidList defines model for UlidList.
type UlidList = []Ulid

// UserEmail User email
type UserEmail = string

// UserFirstLastName First or last name of the user
type UserFirstLastName = string

// UserId Keycloak user ID
type UserId = string

// UserPreferences The object containing user preferences
type UserPreferences struct {
	// PinnedProjects The list of projects a user has pinned on their dashboard
	PinnedProjects PinnedProjects `json:"pinned_projects"`

	// ShowProjectMigrationBanner Should display project migration banner
	ShowProjectMigrationBanner *ShowProjectMigrationBanner `json:"show_project_migration_banner,omitempty"`

	// UserId Keycloak user ID
	UserId UserId `json:"user_id"`
}

// UserSecretKey defines model for UserSecretKey.
type UserSecretKey struct {
	// SecretKey The users secret key
	SecretKey *string `json:"secret_key,omitempty"`
}

// UserWithId defines model for UserWithId.
type UserWithId struct {
	// Email User email
	Email *UserEmail `json:"email,omitempty"`

	// FirstName First or last name of the user
	FirstName *UserFirstLastName `json:"first_name,omitempty"`

	// Id Keycloak user ID
	Id UserId `json:"id"`

	// LastName First or last name of the user
	LastName *UserFirstLastName `json:"last_name,omitempty"`

	// Username Handle of the user
	Username Username `json:"username"`
}

// Username Handle of the user
type Username = string

// UsersWithId defines model for UsersWithId.
type UsersWithId = []UserWithId

// Version defines model for Version.
type Version struct {
	Version string `json:"version"`
}

// Error defines model for Error.
type Error = ErrorResponse

// DeleteUserPreferencesPinnedProjectsParams defines parameters for DeleteUserPreferencesPinnedProjects.
type DeleteUserPreferencesPinnedProjectsParams struct {
	// DeletePinnedParams query parameters
	DeletePinnedParams *struct {
		ProjectSlug *string `json:"project_slug,omitempty"`
	} `form:"delete_pinned_params,omitempty" json:"delete_pinned_params,omitempty"`
}

// GetUserSecretsParams defines parameters for GetUserSecrets.
type GetUserSecretsParams struct {
	UserSecretsParams *struct {
		// Kind Kind of secret
		Kind *SecretKind `json:"kind,omitempty"`
	} `form:"user_secrets_params,omitempty" json:"user_secrets_params,omitempty"`
}

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {
	UserParams *struct {
		// ExactEmail Return the user(s) with an exact match on the email provided
		ExactEmail *string `json:"exact_email,omitempty"`
	} `form:"user_params,omitempty" json:"user_params,omitempty"`
}

// PostUserPreferencesPinnedProjectsJSONRequestBody defines body for PostUserPreferencesPinnedProjects for application/json ContentType.
type PostUserPreferencesPinnedProjectsJSONRequestBody = AddPinnedProject

// PostUserSecretsJSONRequestBody defines body for PostUserSecrets for application/json ContentType.
type PostUserSecretsJSONRequestBody = SecretPost

// PatchUserSecretsSecretIdJSONRequestBody defines body for PatchUserSecretsSecretId for application/json ContentType.
type PatchUserSecretsSecretIdJSONRequestBody = SecretPatch

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetError request
	GetError(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUser request
	GetUser(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUserPreferences request
	GetUserPreferences(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteUserPreferencesDismissProjectMigrationBanner request
	DeleteUserPreferencesDismissProjectMigrationBanner(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostUserPreferencesDismissProjectMigrationBanner request
	PostUserPreferencesDismissProjectMigrationBanner(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteUserPreferencesPinnedProjects request
	DeleteUserPreferencesPinnedProjects(ctx context.Context, params *DeleteUserPreferencesPinnedProjectsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostUserPreferencesPinnedProjectsWithBody request with any body
	PostUserPreferencesPinnedProjectsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostUserPreferencesPinnedProjects(ctx context.Context, body PostUserPreferencesPinnedProjectsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUserSecretKey request
	GetUserSecretKey(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUserSecrets request
	GetUserSecrets(ctx context.Context, params *GetUserSecretsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostUserSecretsWithBody request with any body
	PostUserSecretsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostUserSecrets(ctx context.Context, body PostUserSecretsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteUserSecretsSecretId request
	DeleteUserSecretsSecretId(ctx context.Context, secretId Ulid, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUserSecretsSecretId request
	GetUserSecretsSecretId(ctx context.Context, secretId Ulid, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchUserSecretsSecretIdWithBody request with any body
	PatchUserSecretsSecretIdWithBody(ctx context.Context, secretId Ulid, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PatchUserSecretsSecretId(ctx context.Context, secretId Ulid, body PatchUserSecretsSecretIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUsers request
	GetUsers(ctx context.Context, params *GetUsersParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteUsersUserId request
	DeleteUsersUserId(ctx context.Context, userId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUsersUserId request
	GetUsersUserId(ctx context.Context, userId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetVersion request
	GetVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetError(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetErrorRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUser(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUserRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUserPreferences(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUserPreferencesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteUserPreferencesDismissProjectMigrationBanner(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteUserPreferencesDismissProjectMigrationBannerRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostUserPreferencesDismissProjectMigrationBanner(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostUserPreferencesDismissProjectMigrationBannerRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteUserPreferencesPinnedProjects(ctx context.Context, params *DeleteUserPreferencesPinnedProjectsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteUserPreferencesPinnedProjectsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostUserPreferencesPinnedProjectsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostUserPreferencesPinnedProjectsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostUserPreferencesPinnedProjects(ctx context.Context, body PostUserPreferencesPinnedProjectsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostUserPreferencesPinnedProjectsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUserSecretKey(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUserSecretKeyRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUserSecrets(ctx context.Context, params *GetUserSecretsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUserSecretsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostUserSecretsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostUserSecretsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostUserSecrets(ctx context.Context, body PostUserSecretsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostUserSecretsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteUserSecretsSecretId(ctx context.Context, secretId Ulid, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteUserSecretsSecretIdRequest(c.Server, secretId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUserSecretsSecretId(ctx context.Context, secretId Ulid, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUserSecretsSecretIdRequest(c.Server, secretId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchUserSecretsSecretIdWithBody(ctx context.Context, secretId Ulid, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchUserSecretsSecretIdRequestWithBody(c.Server, secretId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchUserSecretsSecretId(ctx context.Context, secretId Ulid, body PatchUserSecretsSecretIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchUserSecretsSecretIdRequest(c.Server, secretId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUsers(ctx context.Context, params *GetUsersParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUsersRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteUsersUserId(ctx context.Context, userId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteUsersUserIdRequest(c.Server, userId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUsersUserId(ctx context.Context, userId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUsersUserIdRequest(c.Server, userId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetVersionRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetErrorRequest generates requests for GetError
func NewGetErrorRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/error")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetUserRequest generates requests for GetUser
func NewGetUserRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/user")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetUserPreferencesRequest generates requests for GetUserPreferences
func NewGetUserPreferencesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/user/preferences")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteUserPreferencesDismissProjectMigrationBannerRequest generates requests for DeleteUserPreferencesDismissProjectMigrationBanner
func NewDeleteUserPreferencesDismissProjectMigrationBannerRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/user/preferences/dismiss_project_migration_banner")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostUserPreferencesDismissProjectMigrationBannerRequest generates requests for PostUserPreferencesDismissProjectMigrationBanner
func NewPostUserPreferencesDismissProjectMigrationBannerRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/user/preferences/dismiss_project_migration_banner")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteUserPreferencesPinnedProjectsRequest generates requests for DeleteUserPreferencesPinnedProjects
func NewDeleteUserPreferencesPinnedProjectsRequest(server string, params *DeleteUserPreferencesPinnedProjectsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/user/preferences/pinned_projects")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.DeletePinnedParams != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "delete_pinned_params", runtime.ParamLocationQuery, *params.DeletePinnedParams); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostUserPreferencesPinnedProjectsRequest calls the generic PostUserPreferencesPinnedProjects builder with application/json body
func NewPostUserPreferencesPinnedProjectsRequest(server string, body PostUserPreferencesPinnedProjectsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostUserPreferencesPinnedProjectsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostUserPreferencesPinnedProjectsRequestWithBody generates requests for PostUserPreferencesPinnedProjects with any type of body
func NewPostUserPreferencesPinnedProjectsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/user/preferences/pinned_projects")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetUserSecretKeyRequest generates requests for GetUserSecretKey
func NewGetUserSecretKeyRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/user/secret_key")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetUserSecretsRequest generates requests for GetUserSecrets
func NewGetUserSecretsRequest(server string, params *GetUserSecretsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/user/secrets")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.UserSecretsParams != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "user_secrets_params", runtime.ParamLocationQuery, *params.UserSecretsParams); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostUserSecretsRequest calls the generic PostUserSecrets builder with application/json body
func NewPostUserSecretsRequest(server string, body PostUserSecretsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostUserSecretsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostUserSecretsRequestWithBody generates requests for PostUserSecrets with any type of body
func NewPostUserSecretsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/user/secrets")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteUserSecretsSecretIdRequest generates requests for DeleteUserSecretsSecretId
func NewDeleteUserSecretsSecretIdRequest(server string, secretId Ulid) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "secret_id", runtime.ParamLocationPath, secretId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/user/secrets/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetUserSecretsSecretIdRequest generates requests for GetUserSecretsSecretId
func NewGetUserSecretsSecretIdRequest(server string, secretId Ulid) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "secret_id", runtime.ParamLocationPath, secretId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/user/secrets/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPatchUserSecretsSecretIdRequest calls the generic PatchUserSecretsSecretId builder with application/json body
func NewPatchUserSecretsSecretIdRequest(server string, secretId Ulid, body PatchUserSecretsSecretIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchUserSecretsSecretIdRequestWithBody(server, secretId, "application/json", bodyReader)
}

// NewPatchUserSecretsSecretIdRequestWithBody generates requests for PatchUserSecretsSecretId with any type of body
func NewPatchUserSecretsSecretIdRequestWithBody(server string, secretId Ulid, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "secret_id", runtime.ParamLocationPath, secretId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/user/secrets/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetUsersRequest generates requests for GetUsers
func NewGetUsersRequest(server string, params *GetUsersParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.UserParams != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "user_params", runtime.ParamLocationQuery, *params.UserParams); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteUsersUserIdRequest generates requests for DeleteUsersUserId
func NewDeleteUsersUserIdRequest(server string, userId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "user_id", runtime.ParamLocationPath, userId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetUsersUserIdRequest generates requests for GetUsersUserId
func NewGetUsersUserIdRequest(server string, userId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "user_id", runtime.ParamLocationPath, userId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetVersionRequest generates requests for GetVersion
func NewGetVersionRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/version")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetErrorWithResponse request
	GetErrorWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetErrorResponse, error)

	// GetUserWithResponse request
	GetUserWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetUserResponse, error)

	// GetUserPreferencesWithResponse request
	GetUserPreferencesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetUserPreferencesResponse, error)

	// DeleteUserPreferencesDismissProjectMigrationBannerWithResponse request
	DeleteUserPreferencesDismissProjectMigrationBannerWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*DeleteUserPreferencesDismissProjectMigrationBannerResponse, error)

	// PostUserPreferencesDismissProjectMigrationBannerWithResponse request
	PostUserPreferencesDismissProjectMigrationBannerWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostUserPreferencesDismissProjectMigrationBannerResponse, error)

	// DeleteUserPreferencesPinnedProjectsWithResponse request
	DeleteUserPreferencesPinnedProjectsWithResponse(ctx context.Context, params *DeleteUserPreferencesPinnedProjectsParams, reqEditors ...RequestEditorFn) (*DeleteUserPreferencesPinnedProjectsResponse, error)

	// PostUserPreferencesPinnedProjectsWithBodyWithResponse request with any body
	PostUserPreferencesPinnedProjectsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostUserPreferencesPinnedProjectsResponse, error)

	PostUserPreferencesPinnedProjectsWithResponse(ctx context.Context, body PostUserPreferencesPinnedProjectsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostUserPreferencesPinnedProjectsResponse, error)

	// GetUserSecretKeyWithResponse request
	GetUserSecretKeyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetUserSecretKeyResponse, error)

	// GetUserSecretsWithResponse request
	GetUserSecretsWithResponse(ctx context.Context, params *GetUserSecretsParams, reqEditors ...RequestEditorFn) (*GetUserSecretsResponse, error)

	// PostUserSecretsWithBodyWithResponse request with any body
	PostUserSecretsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostUserSecretsResponse, error)

	PostUserSecretsWithResponse(ctx context.Context, body PostUserSecretsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostUserSecretsResponse, error)

	// DeleteUserSecretsSecretIdWithResponse request
	DeleteUserSecretsSecretIdWithResponse(ctx context.Context, secretId Ulid, reqEditors ...RequestEditorFn) (*DeleteUserSecretsSecretIdResponse, error)

	// GetUserSecretsSecretIdWithResponse request
	GetUserSecretsSecretIdWithResponse(ctx context.Context, secretId Ulid, reqEditors ...RequestEditorFn) (*GetUserSecretsSecretIdResponse, error)

	// PatchUserSecretsSecretIdWithBodyWithResponse request with any body
	PatchUserSecretsSecretIdWithBodyWithResponse(ctx context.Context, secretId Ulid, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchUserSecretsSecretIdResponse, error)

	PatchUserSecretsSecretIdWithResponse(ctx context.Context, secretId Ulid, body PatchUserSecretsSecretIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchUserSecretsSecretIdResponse, error)

	// GetUsersWithResponse request
	GetUsersWithResponse(ctx context.Context, params *GetUsersParams, reqEditors ...RequestEditorFn) (*GetUsersResponse, error)

	// DeleteUsersUserIdWithResponse request
	DeleteUsersUserIdWithResponse(ctx context.Context, userId string, reqEditors ...RequestEditorFn) (*DeleteUsersUserIdResponse, error)

	// GetUsersUserIdWithResponse request
	GetUsersUserIdWithResponse(ctx context.Context, userId string, reqEditors ...RequestEditorFn) (*GetUsersUserIdResponse, error)

	// GetVersionWithResponse request
	GetVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVersionResponse, error)
}

type GetErrorResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetErrorResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetErrorResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SelfUserInfo
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r GetUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUserPreferencesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UserPreferences
	JSON404      *ErrorResponse
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r GetUserPreferencesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUserPreferencesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteUserPreferencesDismissProjectMigrationBannerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UserPreferences
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r DeleteUserPreferencesDismissProjectMigrationBannerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteUserPreferencesDismissProjectMigrationBannerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostUserPreferencesDismissProjectMigrationBannerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UserPreferences
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r PostUserPreferencesDismissProjectMigrationBannerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostUserPreferencesDismissProjectMigrationBannerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteUserPreferencesPinnedProjectsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UserPreferences
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r DeleteUserPreferencesPinnedProjectsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteUserPreferencesPinnedProjectsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostUserPreferencesPinnedProjectsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UserPreferences
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r PostUserPreferencesPinnedProjectsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostUserPreferencesPinnedProjectsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUserSecretKeyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UserSecretKey
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r GetUserSecretKeyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUserSecretKeyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUserSecretsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SecretsList
	JSON404      *ErrorResponse
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r GetUserSecretsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUserSecretsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostUserSecretsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *SecretWithId
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r PostUserSecretsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostUserSecretsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteUserSecretsSecretIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r DeleteUserSecretsSecretIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteUserSecretsSecretIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUserSecretsSecretIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SecretWithId
	JSON404      *ErrorResponse
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r GetUserSecretsSecretIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUserSecretsSecretIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PatchUserSecretsSecretIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *SecretWithId
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r PatchUserSecretsSecretIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchUserSecretsSecretIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUsersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UsersWithId
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r GetUsersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUsersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteUsersUserIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r DeleteUsersUserIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteUsersUserIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUsersUserIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UserWithId
	JSON404      *ErrorResponse
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r GetUsersUserIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUsersUserIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetVersionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Version
}

// Status returns HTTPResponse.Status
func (r GetVersionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetVersionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetErrorWithResponse request returning *GetErrorResponse
func (c *ClientWithResponses) GetErrorWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetErrorResponse, error) {
	rsp, err := c.GetError(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetErrorResponse(rsp)
}

// GetUserWithResponse request returning *GetUserResponse
func (c *ClientWithResponses) GetUserWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetUserResponse, error) {
	rsp, err := c.GetUser(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUserResponse(rsp)
}

// GetUserPreferencesWithResponse request returning *GetUserPreferencesResponse
func (c *ClientWithResponses) GetUserPreferencesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetUserPreferencesResponse, error) {
	rsp, err := c.GetUserPreferences(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUserPreferencesResponse(rsp)
}

// DeleteUserPreferencesDismissProjectMigrationBannerWithResponse request returning *DeleteUserPreferencesDismissProjectMigrationBannerResponse
func (c *ClientWithResponses) DeleteUserPreferencesDismissProjectMigrationBannerWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*DeleteUserPreferencesDismissProjectMigrationBannerResponse, error) {
	rsp, err := c.DeleteUserPreferencesDismissProjectMigrationBanner(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteUserPreferencesDismissProjectMigrationBannerResponse(rsp)
}

// PostUserPreferencesDismissProjectMigrationBannerWithResponse request returning *PostUserPreferencesDismissProjectMigrationBannerResponse
func (c *ClientWithResponses) PostUserPreferencesDismissProjectMigrationBannerWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostUserPreferencesDismissProjectMigrationBannerResponse, error) {
	rsp, err := c.PostUserPreferencesDismissProjectMigrationBanner(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostUserPreferencesDismissProjectMigrationBannerResponse(rsp)
}

// DeleteUserPreferencesPinnedProjectsWithResponse request returning *DeleteUserPreferencesPinnedProjectsResponse
func (c *ClientWithResponses) DeleteUserPreferencesPinnedProjectsWithResponse(ctx context.Context, params *DeleteUserPreferencesPinnedProjectsParams, reqEditors ...RequestEditorFn) (*DeleteUserPreferencesPinnedProjectsResponse, error) {
	rsp, err := c.DeleteUserPreferencesPinnedProjects(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteUserPreferencesPinnedProjectsResponse(rsp)
}

// PostUserPreferencesPinnedProjectsWithBodyWithResponse request with arbitrary body returning *PostUserPreferencesPinnedProjectsResponse
func (c *ClientWithResponses) PostUserPreferencesPinnedProjectsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostUserPreferencesPinnedProjectsResponse, error) {
	rsp, err := c.PostUserPreferencesPinnedProjectsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostUserPreferencesPinnedProjectsResponse(rsp)
}

func (c *ClientWithResponses) PostUserPreferencesPinnedProjectsWithResponse(ctx context.Context, body PostUserPreferencesPinnedProjectsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostUserPreferencesPinnedProjectsResponse, error) {
	rsp, err := c.PostUserPreferencesPinnedProjects(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostUserPreferencesPinnedProjectsResponse(rsp)
}

// GetUserSecretKeyWithResponse request returning *GetUserSecretKeyResponse
func (c *ClientWithResponses) GetUserSecretKeyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetUserSecretKeyResponse, error) {
	rsp, err := c.GetUserSecretKey(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUserSecretKeyResponse(rsp)
}

// GetUserSecretsWithResponse request returning *GetUserSecretsResponse
func (c *ClientWithResponses) GetUserSecretsWithResponse(ctx context.Context, params *GetUserSecretsParams, reqEditors ...RequestEditorFn) (*GetUserSecretsResponse, error) {
	rsp, err := c.GetUserSecrets(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUserSecretsResponse(rsp)
}

// PostUserSecretsWithBodyWithResponse request with arbitrary body returning *PostUserSecretsResponse
func (c *ClientWithResponses) PostUserSecretsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostUserSecretsResponse, error) {
	rsp, err := c.PostUserSecretsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostUserSecretsResponse(rsp)
}

func (c *ClientWithResponses) PostUserSecretsWithResponse(ctx context.Context, body PostUserSecretsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostUserSecretsResponse, error) {
	rsp, err := c.PostUserSecrets(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostUserSecretsResponse(rsp)
}

// DeleteUserSecretsSecretIdWithResponse request returning *DeleteUserSecretsSecretIdResponse
func (c *ClientWithResponses) DeleteUserSecretsSecretIdWithResponse(ctx context.Context, secretId Ulid, reqEditors ...RequestEditorFn) (*DeleteUserSecretsSecretIdResponse, error) {
	rsp, err := c.DeleteUserSecretsSecretId(ctx, secretId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteUserSecretsSecretIdResponse(rsp)
}

// GetUserSecretsSecretIdWithResponse request returning *GetUserSecretsSecretIdResponse
func (c *ClientWithResponses) GetUserSecretsSecretIdWithResponse(ctx context.Context, secretId Ulid, reqEditors ...RequestEditorFn) (*GetUserSecretsSecretIdResponse, error) {
	rsp, err := c.GetUserSecretsSecretId(ctx, secretId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUserSecretsSecretIdResponse(rsp)
}

// PatchUserSecretsSecretIdWithBodyWithResponse request with arbitrary body returning *PatchUserSecretsSecretIdResponse
func (c *ClientWithResponses) PatchUserSecretsSecretIdWithBodyWithResponse(ctx context.Context, secretId Ulid, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchUserSecretsSecretIdResponse, error) {
	rsp, err := c.PatchUserSecretsSecretIdWithBody(ctx, secretId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchUserSecretsSecretIdResponse(rsp)
}

func (c *ClientWithResponses) PatchUserSecretsSecretIdWithResponse(ctx context.Context, secretId Ulid, body PatchUserSecretsSecretIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchUserSecretsSecretIdResponse, error) {
	rsp, err := c.PatchUserSecretsSecretId(ctx, secretId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchUserSecretsSecretIdResponse(rsp)
}

// GetUsersWithResponse request returning *GetUsersResponse
func (c *ClientWithResponses) GetUsersWithResponse(ctx context.Context, params *GetUsersParams, reqEditors ...RequestEditorFn) (*GetUsersResponse, error) {
	rsp, err := c.GetUsers(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUsersResponse(rsp)
}

// DeleteUsersUserIdWithResponse request returning *DeleteUsersUserIdResponse
func (c *ClientWithResponses) DeleteUsersUserIdWithResponse(ctx context.Context, userId string, reqEditors ...RequestEditorFn) (*DeleteUsersUserIdResponse, error) {
	rsp, err := c.DeleteUsersUserId(ctx, userId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteUsersUserIdResponse(rsp)
}

// GetUsersUserIdWithResponse request returning *GetUsersUserIdResponse
func (c *ClientWithResponses) GetUsersUserIdWithResponse(ctx context.Context, userId string, reqEditors ...RequestEditorFn) (*GetUsersUserIdResponse, error) {
	rsp, err := c.GetUsersUserId(ctx, userId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUsersUserIdResponse(rsp)
}

// GetVersionWithResponse request returning *GetVersionResponse
func (c *ClientWithResponses) GetVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVersionResponse, error) {
	rsp, err := c.GetVersion(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetVersionResponse(rsp)
}

// ParseGetErrorResponse parses an HTTP response from a GetErrorWithResponse call
func ParseGetErrorResponse(rsp *http.Response) (*GetErrorResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetErrorResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetUserResponse parses an HTTP response from a GetUserWithResponse call
func ParseGetUserResponse(rsp *http.Response) (*GetUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SelfUserInfo
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetUserPreferencesResponse parses an HTTP response from a GetUserPreferencesWithResponse call
func ParseGetUserPreferencesResponse(rsp *http.Response) (*GetUserPreferencesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUserPreferencesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UserPreferences
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseDeleteUserPreferencesDismissProjectMigrationBannerResponse parses an HTTP response from a DeleteUserPreferencesDismissProjectMigrationBannerWithResponse call
func ParseDeleteUserPreferencesDismissProjectMigrationBannerResponse(rsp *http.Response) (*DeleteUserPreferencesDismissProjectMigrationBannerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteUserPreferencesDismissProjectMigrationBannerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UserPreferences
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParsePostUserPreferencesDismissProjectMigrationBannerResponse parses an HTTP response from a PostUserPreferencesDismissProjectMigrationBannerWithResponse call
func ParsePostUserPreferencesDismissProjectMigrationBannerResponse(rsp *http.Response) (*PostUserPreferencesDismissProjectMigrationBannerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostUserPreferencesDismissProjectMigrationBannerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UserPreferences
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseDeleteUserPreferencesPinnedProjectsResponse parses an HTTP response from a DeleteUserPreferencesPinnedProjectsWithResponse call
func ParseDeleteUserPreferencesPinnedProjectsResponse(rsp *http.Response) (*DeleteUserPreferencesPinnedProjectsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteUserPreferencesPinnedProjectsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UserPreferences
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParsePostUserPreferencesPinnedProjectsResponse parses an HTTP response from a PostUserPreferencesPinnedProjectsWithResponse call
func ParsePostUserPreferencesPinnedProjectsResponse(rsp *http.Response) (*PostUserPreferencesPinnedProjectsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostUserPreferencesPinnedProjectsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UserPreferences
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetUserSecretKeyResponse parses an HTTP response from a GetUserSecretKeyWithResponse call
func ParseGetUserSecretKeyResponse(rsp *http.Response) (*GetUserSecretKeyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUserSecretKeyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UserSecretKey
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetUserSecretsResponse parses an HTTP response from a GetUserSecretsWithResponse call
func ParseGetUserSecretsResponse(rsp *http.Response) (*GetUserSecretsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUserSecretsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SecretsList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParsePostUserSecretsResponse parses an HTTP response from a PostUserSecretsWithResponse call
func ParsePostUserSecretsResponse(rsp *http.Response) (*PostUserSecretsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostUserSecretsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest SecretWithId
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseDeleteUserSecretsSecretIdResponse parses an HTTP response from a DeleteUserSecretsSecretIdWithResponse call
func ParseDeleteUserSecretsSecretIdResponse(rsp *http.Response) (*DeleteUserSecretsSecretIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteUserSecretsSecretIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetUserSecretsSecretIdResponse parses an HTTP response from a GetUserSecretsSecretIdWithResponse call
func ParseGetUserSecretsSecretIdResponse(rsp *http.Response) (*GetUserSecretsSecretIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUserSecretsSecretIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SecretWithId
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParsePatchUserSecretsSecretIdResponse parses an HTTP response from a PatchUserSecretsSecretIdWithResponse call
func ParsePatchUserSecretsSecretIdResponse(rsp *http.Response) (*PatchUserSecretsSecretIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchUserSecretsSecretIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest SecretWithId
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetUsersResponse parses an HTTP response from a GetUsersWithResponse call
func ParseGetUsersResponse(rsp *http.Response) (*GetUsersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUsersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UsersWithId
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseDeleteUsersUserIdResponse parses an HTTP response from a DeleteUsersUserIdWithResponse call
func ParseDeleteUsersUserIdResponse(rsp *http.Response) (*DeleteUsersUserIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteUsersUserIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetUsersUserIdResponse parses an HTTP response from a GetUsersUserIdWithResponse call
func ParseGetUsersUserIdResponse(rsp *http.Response) (*GetUsersUserIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUsersUserIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UserWithId
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetVersionResponse parses an HTTP response from a GetVersionWithResponse call
func ParseGetVersionResponse(rsp *http.Response) (*GetVersionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetVersionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Version
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbe3PbNhL/KhhcZ5q0pPWI0zT6586N26vbpOdJ7HQmtk8DESsRNQmwAGhb9ei73+DB",
	"l0jJVO2kbub+skURi33+dhcL3eJIpJngwLXCk1ssQWWCK7AfvpdSSPNPJLgGrs2/JMsSFhHNBB/8pgQ3",
	"z1QUQ0rMf19ImOMJ/segojpw36qBpfbW08er1SrAFFQkWWaI4Qk+iQG5l9FcSESSBO3f3CDCKXp+c4Mq",
	"1sxST9VsekDpMeMc6LEUv0Hk2KSUGbIkOZYiA6mZEWlOEgUBzmqPbs0ns2qqknxxlwx+h3fmVcOFhN9z",
	"JoHiyVmTzkWA9TIDPMFiZnlaBbipALdzjQ8otN18HAlqX4YbkmYJ4Mlof7gfYLiJklyxK3jDOEvzFE+0",
	"zCHAafFxWHLAuIYFSGwVrglLGuTwAUqFBOS+AopE5hSHUlCKLACpWFwzvkDXMdFIx4AyKWYJpOiaKFzu",
	"orRkfGE28euau7wTKejYkgGu0bUUfIFClCVAFCAtl4gsCOMoIRpkm+qarq1Sqp3a2l573+m20yg3GZPW",
	"nU9YCkqTNDOMtz2TEg3WFzVLwapBQSRBI6YQFxpdkYRRRPjSavOJjpkyXzFuntlFfwgOT3FQU8p4+GwY",
	"jkbhcHQyejF5Np6Mvz09efX1cDQZDnGA50KmROMJNnuHhgQOMM+ThMzMcmfwlvrfCMrmPkQPiYYdxbkm",
	"CkUSiDauIFFqqQGtJCLJNVlawU5PXq3LM362Js+HTXK0+G7EsOrmOmFKIzFHPtYUIihXIFFMFMrseiS4",
	"kYZJRImKZ4JIirdFvH3ANKRqh9ivUKyUg0hJltbvWi5WB41OqQwfRg6KtECMAtdsvkSkkLKhYiPuIF2G",
	"1Xcp46+BL3SMJ88CnBGtQRrK/z0j4R8H4Ydh+PLi6ydn073z83BwUX/49Kvi6T9rj7/oNE6H8B9dlhYX",
	"76yLHsKc5In+gSXASdrBR/GNYWHBruxf672Fi8fAUSpybnyccfQW+GWORntDpEApJrg65w1GD4km4btn",
	"odt/OjKckpuC05cvG4yPNhhhen4e7l181aleR/hnxmlbGvPU+Lxj3vDFDb6f4QVwkCTBAVZayCYOrpP+",
	"pVNRxmBWUWJeRFK1S5Ugjo/QibgEfpfYG/Y+JjqK70zKTc7cSpSCJpRoYiw4gxKMWhFNnUtM5zWf2BbL",
	"3Y60MlIX6WCq6/lga2HTkUJWAe7Pxy9+8yuS5D2XvLevdsKNV7pQ+kF07nPB30Lllz6ASJL8Z44nZ304",
	"skG3uggKgfCkDKxPZ8R6rWK3LOhcbDTw+2KfTiPa1Uibii0i3NjRViFwo5tB/Hw4HPYM41+Zjo/ojj51",
	"4MG1hJU1JyKaTCPBOURayCmjd2bh04TR10xpV80+PhdktI8EdWft66IBTmuV3ZT60m7b8lYp+Kc82ifF",
	"qbPhVCVC72apNQdnBky8l7dM2CWl19VmToIuR9ocOsqy1Qqdg7K8dPQN3V6VYSM+WiWh2TWZnyqQR3wu",
	"dowfs8QUz0xwRGYidw1YlEsJXCdLlIjFwhUxJnu34gtS3+5tNZQC+b19cRXgOZNKT/s4iVn2g3n7NVGl",
	"r/Rwf6MIqyampoSmjNeyyQYt/BqDjkFa2W2VYtoQlCVEG+0gS4UpLYkW0jQtXOiqypoJkQDhZseE3Ec2",
	"s3PfxQ5Zuhy/pFJTQKerxuLaV91v2MIhzXeEc5AdoB+LPKGIMpUlZFnU2igt1qGZW9ilEwtHLYqnr48O",
	"i/Kd2ZW1pDH+ppEyzMd6xTsMX1ycDcOXB+GPP/385pfj8OR9+OHidvx81Vn7ljjRtxErAHQ9zCo/botj",
	"nMYFQ72yVSKF0BjkXwvz3V4k0k4OW97Q0XJIAx0SGRcra+rCXxub/iTitUp6/PybO3OwD5t2dwDLKBHk",
	"0sXF0WFjq/mLfTIefzsLRy9eDsP98YtvQjJ/Pg/Hz6Px/ngfXs6GEW4a7yD8QMI/TB94O1pVn8KLr7/Y",
	"pJpjCXOQwCOHOTugm+k/nMejSHBNGGd84STJakRb/bvt9KdZ7ahga+PePFgwGS0W18XyaRkl01kZXlvR",
	"fnNgepCY9kfBNYQoVgctGbsgwhDxFQIsdzz19Cn00i1sm8VwUjbM5q2uI7lOjnrWiaWX3jZyDv6JcIuN",
	"tIhPSTgVaXjpHT206qkhOT4UUMfVWlgX9d3fKCk+qhS1yem6j11+JJwmm3GvaZVdjxLMtqpyrX6JovLG",
	"9XQR4Jyz33M4cnS0zGEV4PcgFXMzjabLXFVfbD+YLl7sPJFWEOWS6eU7w58jLBiN7N8M+BF95QrYU5ng",
	"CR6QXMcDCSRJ1cB2UYO9a0iS8JKLaz4wKxgNI8HnbJE7GKqCtEHPDVuYrz7XY92ei8krFoEpq4zpUsJM",
	"yRBdAqd2FGN330NH2pQWV4yCQqxVmFrECMqj2eCcR4nIKfKHUwEiUQRKIS2QsVWuAUlQIpcRKHsSnZoW",
	"VfhCj/GF2rPHcJpp6z+ukTwkmqB3jl+FDo6PTKtcWAdfjYyljfAkY3iCn+0N98Yuw8VW34NyyrIA7RXv",
	"dGf8Cv8btBt6Bc1J2P54/GnnYI5N6zR5mhK5dMwhgpSNJ/dCORND10zHSGmic4UiQQEZjs3ygY3DLfKe",
	"ujhtiDseDh9M3Ebzs0Hajf3MqnYs071NybfTa4fK2K4tlCYLVSRjhS9KLQ6yZqGzTaPHjfLloyl3fasN",
	"+m1VVKsA7w/3P61Ll4MaLuq8IEWugD6IpdfFtNi1g7GndRV1231AmUqZUlurRwoJuMOZpm8c2udrNjt0",
	"BDdUlI/AdzJqZ4FdPnQvi72FVFwB8gr1LWq7d91uowBn/qC7qepjofT/Fe0UfXgvDXdGQUcHtpPTr7Vk",
	"JkFLkoI2gDs5W69Rfs9BLlHtFXtim9iLEW4IzsrXiqPFiWdoWrBqVpuVlc3ucUekmhX064uUXrqGXMjU",
	"Dhs+96gWHJC/w+Pn8lll7IeJ55YPmToclP5O0OWDqbN1t2jVrPh94/DZmvOAUkTWTNgTL5onDNuKpeoM",
	"4yNrstpo0/Wz8ryjaGM3lQ5759y2TsBpJhgvrwFl+SxhUbL03Q6bJWDamIcob2rsdB7PeJsUw4uWKVQ/",
	"O3TAcQ+0tZ7g97kn2O46GPtrAbc+UtpS+X6pyqnSX1Z8UwHOSeGmOUH9cz5pRLYI7wVztzbdVk8uYamQ",
	"4Mnyaadr3oXzlSt+DFSvXZHoheejB965OJRq28qP71Vu0WOeJ8myvIFxX3u9snQQQRyuC+goOqS1bmgz",
	"hgxuPa4zuupX9nlTuj9HtI0uFk4youMKTco98Lpxgr5wb4dEHZG/v+HeWnX70Ylkbz9SRvmXDxUvTiWI",
	"VJchuuKiB0A/FlUOP1lYVBb6bNDTn+ZVBcdsiayROsGyuEK3hpbm8eNwjI8G0lbyvwNKx4QvHgKlLZ3t",
	"KFGA8p0V3T1qufvVcHBDIj2F7mn8W9C55GXeeaKeuvNrwpFdh1JjdH+T243ti8EDfYz9ttoOXMWtIlez",
	"M+5v27uRS3WtHql8psC+aX9p4X48UMz3nz5cuZZ7x9h0zq0Gt34O3TPDKz++7IM61YR7M+asG7h3Erc4",
	"bVJ4IzKb+fwBIbxK6BlEbM4ix8Bs6X+BUN7NsNcy1tW9PdV/ep0+bExsDwmfL/yJxeeW0/+MN5jgq02Z",
	"N7lGMaH+iNYrtthxMmlAzQtQnJ14jHOUiuG3dWI39j7DboiNL4w7mrcLJ8/9BDxjA0o0wauL1f8CAAD/",
	"/2LmUM6qOAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
